name: Robert Pisanij
url: https://rcjpisani.github.io
title: "Robert Pisani (rcjpisani)"
description: "Software Engineer, Leader, Musician, Lifelong Learner"

date_format: "%Y-%b-%d"
timezone: America/Toronto
